/**
 * Performance Dashboard JavaScript
 * Fetches and displays live trading data
 */

const API_BASE = '/api';  // Would be actual API endpoint in production
const REFRESH_INTERVAL = 60000;  // 60 seconds

let performanceData = {
    current_capital: 0,
    total_pnl: 0,
    win_rate: 0,
    open_positions: 0,
    total_trades: 0,
    max_drawdown_pct: 0,
    positions: [],
    recent_trades: []
};

/**
 * Fetch performance data from database
 */
async function fetchPerformanceData() {
    try {
        // In production, this would fetch from an API
        // For now, we'll try to load from a JSON file generated by the trader
        const response = await fetch('performance.json');
        
        if (response.ok) {
            performanceData = await response.json();
            updateDashboard();
        } else {
            showAlert('Unable to load performance data. Is the trading agent running?', 'error');
        }
    } catch (error) {
        console.error('Error fetching data:', error);
        // Use mock data for development
        useMockData();
    }
}

/**
 * Update dashboard with current data
 */
function updateDashboard() {
    // Update metrics
    document.getElementById('current-capital').textContent = 
        `$${performanceData.current_capital.toLocaleString('en-US', {minimumFractionDigits: 2, maximumFractionDigits: 2})}`;
    
    const pnlElement = document.getElementById('total-pnl');
    const pnl = performanceData.total_pnl;
    pnlElement.textContent = `$${pnl.toLocaleString('en-US', {minimumFractionDigits: 2, maximumFractionDigits: 2})}`;
    pnlElement.className = 'metric-value ' + (pnl >= 0 ? 'positive' : 'negative');
    
    document.getElementById('win-rate').textContent = 
        `${performanceData.win_rate.toFixed(1)}%`;
    
    document.getElementById('open-positions').textContent = 
        performanceData.open_positions;
    
    document.getElementById('total-trades').textContent = 
        performanceData.total_trades;
    
    document.getElementById('max-drawdown').textContent = 
        `${performanceData.max_drawdown_pct.toFixed(2)}%`;
    
    // Update positions table
    updatePositionsTable();
    
    // Update trades table
    updateTradesTable();
    
    // Update timestamp
    document.getElementById('last-update').textContent = 
        new Date().toLocaleString();
    
    // Check for alerts
    checkAlerts();
}

/**
 * Update positions table
 */
function updatePositionsTable() {
    const tbody = document.getElementById('positions-body');
    
    if (!performanceData.positions || performanceData.positions.length === 0) {
        tbody.innerHTML = '<tr><td colspan="7" style="text-align: center; color: #999;">No open positions</td></tr>';
        return;
    }
    
    tbody.innerHTML = performanceData.positions.map(pos => `
        <tr>
            <td>${pos.market_question.substring(0, 60)}...</td>
            <td>${pos.side}</td>
            <td>${pos.size.toFixed(2)}</td>
            <td>$${pos.entry_price.toFixed(4)}</td>
            <td>$${pos.current_price.toFixed(4)}</td>
            <td class="${pos.unrealized_pnl >= 0 ? 'positive' : 'negative'}">
                $${pos.unrealized_pnl.toFixed(2)}
            </td>
            <td class="status-${pos.status.toLowerCase()}">${pos.status}</td>
        </tr>
    `).join('');
}

/**
 * Update trades table
 */
function updateTradesTable() {
    const tbody = document.getElementById('trades-body');
    
    if (!performanceData.recent_trades || performanceData.recent_trades.length === 0) {
        tbody.innerHTML = '<tr><td colspan="7" style="text-align: center; color: #999;">No trades yet</td></tr>';
        return;
    }
    
    tbody.innerHTML = performanceData.recent_trades.map(trade => `
        <tr>
            <td>${new Date(trade.timestamp).toLocaleString()}</td>
            <td>${trade.market_question.substring(0, 40)}...</td>
            <td>${trade.side}</td>
            <td>${trade.size.toFixed(2)}</td>
            <td>$${trade.price.toFixed(4)}</td>
            <td>$${trade.value_usd.toFixed(2)}</td>
            <td>${trade.status}</td>
        </tr>
    `).join('');
}

/**
 * Check for alerts
 */
function checkAlerts() {
    const alertContainer = document.getElementById('alert-container');
    alertContainer.innerHTML = '';
    
    // Check drawdown
    if (performanceData.max_drawdown_pct > 15) {
        showAlert(`High drawdown: ${performanceData.max_drawdown_pct.toFixed(2)}%`, 'error');
    }
    
    // Check if trading
    if (performanceData.total_trades === 0) {
        showAlert('No trades executed yet. System may be in dry-run mode.', 'warning');
    }
}

/**
 * Show alert message
 */
function showAlert(message, type = 'warning') {
    const alertContainer = document.getElementById('alert-container');
    const alertDiv = document.createElement('div');
    alertDiv.className = `alert-box ${type}`;
    alertDiv.innerHTML = `<strong>${type === 'error' ? '⚠️ Alert:' : 'ℹ️ Info:'}</strong> ${message}`;
    alertContainer.appendChild(alertDiv);
}

/**
 * Use mock data for development/testing
 */
function useMockData() {
    performanceData = {
        current_capital: 2000,
        total_pnl: 0,
        win_rate: 0,
        open_positions: 0,
        total_trades: 0,
        max_drawdown_pct: 0,
        positions: [],
        recent_trades: []
    };
    updateDashboard();
}

/**
 * Initialize dashboard
 */
function init() {
    fetchPerformanceData();
    
    // Auto-refresh
    setInterval(fetchPerformanceData, REFRESH_INTERVAL);
}

// Start when page loads
window.addEventListener('DOMContentLoaded', init);


